[package]
name = "iced_wgpu"
version = "0.2.2"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A wgpu renderer for Iced"
license = "MIT AND OFL-1.1"
repository = "https://github.com/hecrj/iced"

[features]
svg = ["resvg"]
canvas = ["lyon"]

[dependencies]
wgpu = "0.5"
wgpu_glyph = { git = "https://github.com/hecrj/wgpu_glyph.git", branch = "feature/update-glyph-brush" }
zerocopy = "0.3"
glyph_brush = "0.7"
raw-window-handle = "0.3"
glam = "0.8"
font-kit = "0.6"
log = "0.4"
guillotiere = "0.5"
# Pin `gfx-memory` until https://github.com/gfx-rs/wgpu-rs/issues/261 is
# resolved
gfx-memory = "=0.1.1"

[dependencies.iced_native]
version = "0.2"
path = "../native"

[dependencies.iced_style]
version = "0.1"
path = "../style"

[dependencies.image]
version = "0.23"
optional = true

[dependencies.resvg]
version = "0.9"
features = ["raqote-backend"]
optional = true

[dependencies.lyon]
version = "0.15"
optional = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
